name: Run Python Files

on:
  push:

permissions:
  id-token: write
  pull-requests: write
  contents: read
  repository-projects: read

jobs:
  run_python_file:
    runs-on: ubuntu-latest
    outputs:
      module_paths_chunks: ${{ steps.get-pods.outputs.module_paths_chunks }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
    - id: get-pods
      working-directory: .github/scripts
      run: |
        python find_pods.py sandbox
  print_outputs:
    runs-on: ubuntu-latest
    needs: run_python_file
    strategy:
      fail-fast: true
      matrix:
        module_path: ${{ fromJSON(needs.run_python_file.outputs.module_paths_chunks) }}
    steps:
    - name: print outputs
      working-directory: ${{ matrix.module_path }}
      run: pwd
