name: Run Python Files

on:
  push:

permissions:
  id-token: write
  pull-requests: write
  contents: read
  repository-projects: read

jobs:
  run_python_file:
    runs-on: ubuntu-latest
    outputs:
      module_paths_chunks: ${{ steps.get-pods.outputs }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
    - id: get-pods
      run: |
        python ../scripts/find_pods.py
  print_outputs:
    runs-on: ubuntu-latest
    needs: run_python_file
    steps:
    - name: print outputs
      run: echo ${{ needs.run_python_file.outputs.module_paths_chunks }}
